modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = 'LGPL'

[[mods]]
modId = "refinedcrafterproxy"
version = "${file.jarVersion}"
displayName = "Refined Crafter Proxy"
credits = ""
authors = "StevenDoesStuffs"
description = '''
Allows multiple crafters to use the same pattern set.
'''
[[dependencies.refinedcrafterproxy]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.refinedcrafterproxy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.refinedcrafterproxy]]
modId = "refinedstorage"
mandatory = true
versionRange = "[1.12,)"
ordering = "AFTER"
side = "BOTH"
